import Foundation

enum CurrencyType: String, Codable, Hashable, CaseIterable {
    case fiat
    case crypto
}

struct Currency: Identifiable, Hashable, Codable {
    let code: String
    let name: String
    let symbol: String
    let type: CurrencyType
    let flag: String?

    var id: String { code }
    var isCrypto: Bool { type == .crypto }
}

extension Currency {
    // All currencies supported by api.exchangerate-api.com/v4 (160+ currencies, no API key)
    static let allFiat: [Currency] = [
        Currency(code: "AED", name: "UAE Dirham",                    symbol: "د.إ", type: .fiat, flag: "🇦🇪"),
        Currency(code: "AFN", name: "Afghan Afghani",                symbol: "؋",   type: .fiat, flag: "🇦🇫"),
        Currency(code: "ALL", name: "Albanian Lek",                  symbol: "L",   type: .fiat, flag: "🇦🇱"),
        Currency(code: "AMD", name: "Armenian Dram",                 symbol: "֏",   type: .fiat, flag: "🇦🇲"),
        Currency(code: "ANG", name: "Antillean Guilder",             symbol: "ƒ",   type: .fiat, flag: "🇨🇼"),
        Currency(code: "AOA", name: "Angolan Kwanza",                symbol: "Kz",  type: .fiat, flag: "🇦🇴"),
        Currency(code: "ARS", name: "Argentine Peso",                symbol: "$",   type: .fiat, flag: "🇦🇷"),
        Currency(code: "AUD", name: "Australian Dollar",             symbol: "$",   type: .fiat, flag: "🇦🇺"),
        Currency(code: "AWG", name: "Aruban Florin",                 symbol: "ƒ",   type: .fiat, flag: "🇦🇼"),
        Currency(code: "AZN", name: "Azerbaijani Manat",             symbol: "₼",   type: .fiat, flag: "🇦🇿"),
        Currency(code: "BAM", name: "Bosnia-Herzegovina Mark",       symbol: "KM",  type: .fiat, flag: "🇧🇦"),
        Currency(code: "BBD", name: "Barbadian Dollar",              symbol: "$",   type: .fiat, flag: "🇧🇧"),
        Currency(code: "BDT", name: "Bangladeshi Taka",              symbol: "৳",   type: .fiat, flag: "🇧🇩"),
        Currency(code: "BGN", name: "Bulgarian Lev",                 symbol: "лв",  type: .fiat, flag: "🇧🇬"),
        Currency(code: "BHD", name: "Bahraini Dinar",                symbol: "BD",  type: .fiat, flag: "🇧🇭"),
        Currency(code: "BIF", name: "Burundian Franc",               symbol: "Fr",  type: .fiat, flag: "🇧🇮"),
        Currency(code: "BMD", name: "Bermudian Dollar",              symbol: "$",   type: .fiat, flag: "🇧🇲"),
        Currency(code: "BND", name: "Brunei Dollar",                 symbol: "$",   type: .fiat, flag: "🇧🇳"),
        Currency(code: "BOB", name: "Bolivian Boliviano",            symbol: "Bs.", type: .fiat, flag: "🇧🇴"),
        Currency(code: "BRL", name: "Brazilian Real",                symbol: "R$",  type: .fiat, flag: "🇧🇷"),
        Currency(code: "BSD", name: "Bahamian Dollar",               symbol: "$",   type: .fiat, flag: "🇧🇸"),
        Currency(code: "BTN", name: "Bhutanese Ngultrum",            symbol: "Nu",  type: .fiat, flag: "🇧🇹"),
        Currency(code: "BWP", name: "Botswanan Pula",                symbol: "P",   type: .fiat, flag: "🇧🇼"),
        Currency(code: "BYN", name: "Belarusian Ruble",              symbol: "Br",  type: .fiat, flag: "🇧🇾"),
        Currency(code: "BZD", name: "Belize Dollar",                 symbol: "$",   type: .fiat, flag: "🇧🇿"),
        Currency(code: "CAD", name: "Canadian Dollar",               symbol: "$",   type: .fiat, flag: "🇨🇦"),
        Currency(code: "CDF", name: "Congolese Franc",               symbol: "Fr",  type: .fiat, flag: "🇨🇩"),
        Currency(code: "CHF", name: "Swiss Franc",                   symbol: "Fr",  type: .fiat, flag: "🇨🇭"),
        Currency(code: "CLP", name: "Chilean Peso",                  symbol: "$",   type: .fiat, flag: "🇨🇱"),
        Currency(code: "CNY", name: "Chinese Yuan",                  symbol: "¥",   type: .fiat, flag: "🇨🇳"),
        Currency(code: "COP", name: "Colombian Peso",                symbol: "$",   type: .fiat, flag: "🇨🇴"),
        Currency(code: "CRC", name: "Costa Rican Colón",             symbol: "₡",   type: .fiat, flag: "🇨🇷"),
        Currency(code: "CUP", name: "Cuban Peso",                    symbol: "$",   type: .fiat, flag: "🇨🇺"),
        Currency(code: "CVE", name: "Cape Verdean Escudo",           symbol: "$",   type: .fiat, flag: "🇨🇻"),
        Currency(code: "CZK", name: "Czech Koruna",                  symbol: "Kč",  type: .fiat, flag: "🇨🇿"),
        Currency(code: "DJF", name: "Djiboutian Franc",              symbol: "Fr",  type: .fiat, flag: "🇩🇯"),
        Currency(code: "DKK", name: "Danish Krone",                  symbol: "kr",  type: .fiat, flag: "🇩🇰"),
        Currency(code: "DOP", name: "Dominican Peso",                symbol: "$",   type: .fiat, flag: "🇩🇴"),
        Currency(code: "DZD", name: "Algerian Dinar",                symbol: "د.ج", type: .fiat, flag: "🇩🇿"),
        Currency(code: "EGP", name: "Egyptian Pound",                symbol: "£",   type: .fiat, flag: "🇪🇬"),
        Currency(code: "ERN", name: "Eritrean Nakfa",                symbol: "Nfk", type: .fiat, flag: "🇪🇷"),
        Currency(code: "ETB", name: "Ethiopian Birr",                symbol: "Br",  type: .fiat, flag: "🇪🇹"),
        Currency(code: "EUR", name: "Euro",                          symbol: "€",   type: .fiat, flag: "🇪🇺"),
        Currency(code: "FJD", name: "Fijian Dollar",                 symbol: "$",   type: .fiat, flag: "🇫🇯"),
        Currency(code: "FKP", name: "Falkland Islands Pound",        symbol: "£",   type: .fiat, flag: "🇫🇰"),
        Currency(code: "GBP", name: "British Pound",                 symbol: "£",   type: .fiat, flag: "🇬🇧"),
        Currency(code: "GEL", name: "Georgian Lari",                 symbol: "₾",   type: .fiat, flag: "🇬🇪"),
        Currency(code: "GHS", name: "Ghanaian Cedi",                 symbol: "₵",   type: .fiat, flag: "🇬🇭"),
        Currency(code: "GIP", name: "Gibraltar Pound",               symbol: "£",   type: .fiat, flag: "🇬🇮"),
        Currency(code: "GMD", name: "Gambian Dalasi",                symbol: "D",   type: .fiat, flag: "🇬🇲"),
        Currency(code: "GNF", name: "Guinean Franc",                 symbol: "Fr",  type: .fiat, flag: "🇬🇳"),
        Currency(code: "GTQ", name: "Guatemalan Quetzal",            symbol: "Q",   type: .fiat, flag: "🇬🇹"),
        Currency(code: "GYD", name: "Guyanaese Dollar",              symbol: "$",   type: .fiat, flag: "🇬🇾"),
        Currency(code: "HKD", name: "Hong Kong Dollar",              symbol: "HK$", type: .fiat, flag: "🇭🇰"),
        Currency(code: "HNL", name: "Honduran Lempira",              symbol: "L",   type: .fiat, flag: "🇭🇳"),
        Currency(code: "HRK", name: "Croatian Kuna",                 symbol: "kn",  type: .fiat, flag: "🇭🇷"),
        Currency(code: "HTG", name: "Haitian Gourde",                symbol: "G",   type: .fiat, flag: "🇭🇹"),
        Currency(code: "HUF", name: "Hungarian Forint",              symbol: "Ft",  type: .fiat, flag: "🇭🇺"),
        Currency(code: "IDR", name: "Indonesian Rupiah",             symbol: "Rp",  type: .fiat, flag: "🇮🇩"),
        Currency(code: "ILS", name: "Israeli Shekel",                symbol: "₪",   type: .fiat, flag: "🇮🇱"),
        Currency(code: "INR", name: "Indian Rupee",                  symbol: "₹",   type: .fiat, flag: "🇮🇳"),
        Currency(code: "IQD", name: "Iraqi Dinar",                   symbol: "ع.د", type: .fiat, flag: "🇮🇶"),
        Currency(code: "IRR", name: "Iranian Rial",                  symbol: "﷼",   type: .fiat, flag: "🇮🇷"),
        Currency(code: "ISK", name: "Icelandic Króna",               symbol: "kr",  type: .fiat, flag: "🇮🇸"),
        Currency(code: "JMD", name: "Jamaican Dollar",               symbol: "$",   type: .fiat, flag: "🇯🇲"),
        Currency(code: "JOD", name: "Jordanian Dinar",               symbol: "JD",  type: .fiat, flag: "🇯🇴"),
        Currency(code: "JPY", name: "Japanese Yen",                  symbol: "¥",   type: .fiat, flag: "🇯🇵"),
        Currency(code: "KES", name: "Kenyan Shilling",               symbol: "Ksh", type: .fiat, flag: "🇰🇪"),
        Currency(code: "KGS", name: "Kyrgystani Som",                symbol: "с",   type: .fiat, flag: "🇰🇬"),
        Currency(code: "KHR", name: "Cambodian Riel",                symbol: "៛",   type: .fiat, flag: "🇰🇭"),
        Currency(code: "KMF", name: "Comorian Franc",                symbol: "Fr",  type: .fiat, flag: "🇰🇲"),
        Currency(code: "KRW", name: "South Korean Won",              symbol: "₩",   type: .fiat, flag: "🇰🇷"),
        Currency(code: "KWD", name: "Kuwaiti Dinar",                 symbol: "KD",  type: .fiat, flag: "🇰🇼"),
        Currency(code: "KYD", name: "Cayman Islands Dollar",         symbol: "$",   type: .fiat, flag: "🇰🇾"),
        Currency(code: "KZT", name: "Kazakhstani Tenge",             symbol: "₸",   type: .fiat, flag: "🇰🇿"),
        Currency(code: "LAK", name: "Laotian Kip",                   symbol: "₭",   type: .fiat, flag: "🇱🇦"),
        Currency(code: "LBP", name: "Lebanese Pound",                symbol: "£",   type: .fiat, flag: "🇱🇧"),
        Currency(code: "LKR", name: "Sri Lankan Rupee",              symbol: "₨",   type: .fiat, flag: "🇱🇰"),
        Currency(code: "LRD", name: "Liberian Dollar",               symbol: "$",   type: .fiat, flag: "🇱🇷"),
        Currency(code: "LSL", name: "Lesotho Loti",                  symbol: "L",   type: .fiat, flag: "🇱🇸"),
        Currency(code: "LYD", name: "Libyan Dinar",                  symbol: "ل.د", type: .fiat, flag: "🇱🇾"),
        Currency(code: "MAD", name: "Moroccan Dirham",               symbol: "MAD", type: .fiat, flag: "🇲🇦"),
        Currency(code: "MDL", name: "Moldovan Leu",                  symbol: "L",   type: .fiat, flag: "🇲🇩"),
        Currency(code: "MGA", name: "Malagasy Ariary",               symbol: "Ar",  type: .fiat, flag: "🇲🇬"),
        Currency(code: "MKD", name: "Macedonian Denar",              symbol: "ден", type: .fiat, flag: "🇲🇰"),
        Currency(code: "MMK", name: "Myanmar Kyat",                  symbol: "K",   type: .fiat, flag: "🇲🇲"),
        Currency(code: "MNT", name: "Mongolian Tugrik",              symbol: "₮",   type: .fiat, flag: "🇲🇳"),
        Currency(code: "MOP", name: "Macanese Pataca",               symbol: "P",   type: .fiat, flag: "🇲🇴"),
        Currency(code: "MRU", name: "Mauritanian Ouguiya",           symbol: "UM",  type: .fiat, flag: "🇲🇷"),
        Currency(code: "MUR", name: "Mauritian Rupee",               symbol: "₨",   type: .fiat, flag: "🇲🇺"),
        Currency(code: "MVR", name: "Maldivian Rufiyaa",             symbol: "Rf",  type: .fiat, flag: "🇲🇻"),
        Currency(code: "MWK", name: "Malawian Kwacha",               symbol: "MK",  type: .fiat, flag: "🇲🇼"),
        Currency(code: "MXN", name: "Mexican Peso",                  symbol: "$",   type: .fiat, flag: "🇲🇽"),
        Currency(code: "MYR", name: "Malaysian Ringgit",             symbol: "RM",  type: .fiat, flag: "🇲🇾"),
        Currency(code: "MZN", name: "Mozambican Metical",            symbol: "MT",  type: .fiat, flag: "🇲🇿"),
        Currency(code: "NAD", name: "Namibian Dollar",               symbol: "$",   type: .fiat, flag: "🇳🇦"),
        Currency(code: "NGN", name: "Nigerian Naira",                symbol: "₦",   type: .fiat, flag: "🇳🇬"),
        Currency(code: "NIO", name: "Nicaraguan Córdoba",            symbol: "C$",  type: .fiat, flag: "🇳🇮"),
        Currency(code: "NOK", name: "Norwegian Krone",               symbol: "kr",  type: .fiat, flag: "🇳🇴"),
        Currency(code: "NPR", name: "Nepalese Rupee",                symbol: "₨",   type: .fiat, flag: "🇳🇵"),
        Currency(code: "NZD", name: "New Zealand Dollar",            symbol: "$",   type: .fiat, flag: "🇳🇿"),
        Currency(code: "OMR", name: "Omani Rial",                    symbol: "ر.ع.", type: .fiat, flag: "🇴🇲"),
        Currency(code: "PAB", name: "Panamanian Balboa",             symbol: "B/.", type: .fiat, flag: "🇵🇦"),
        Currency(code: "PEN", name: "Peruvian Sol",                  symbol: "S/.", type: .fiat, flag: "🇵🇪"),
        Currency(code: "PGK", name: "Papua New Guinean Kina",        symbol: "K",   type: .fiat, flag: "🇵🇬"),
        Currency(code: "PHP", name: "Philippine Peso",               symbol: "₱",   type: .fiat, flag: "🇵🇭"),
        Currency(code: "PKR", name: "Pakistani Rupee",               symbol: "₨",   type: .fiat, flag: "🇵🇰"),
        Currency(code: "PLN", name: "Polish Zloty",                  symbol: "zł",  type: .fiat, flag: "🇵🇱"),
        Currency(code: "PYG", name: "Paraguayan Guarani",            symbol: "₲",   type: .fiat, flag: "🇵🇾"),
        Currency(code: "QAR", name: "Qatari Rial",                   symbol: "ر.ق", type: .fiat, flag: "🇶🇦"),
        Currency(code: "RON", name: "Romanian Leu",                  symbol: "lei", type: .fiat, flag: "🇷🇴"),
        Currency(code: "RSD", name: "Serbian Dinar",                 symbol: "din", type: .fiat, flag: "🇷🇸"),
        Currency(code: "RUB", name: "Russian Ruble",                 symbol: "₽",   type: .fiat, flag: "🇷🇺"),
        Currency(code: "RWF", name: "Rwandan Franc",                 symbol: "Fr",  type: .fiat, flag: "🇷🇼"),
        Currency(code: "SAR", name: "Saudi Riyal",                   symbol: "ر.س", type: .fiat, flag: "🇸🇦"),
        Currency(code: "SBD", name: "Solomon Islands Dollar",        symbol: "$",   type: .fiat, flag: "🇸🇧"),
        Currency(code: "SCR", name: "Seychellois Rupee",             symbol: "₨",   type: .fiat, flag: "🇸🇨"),
        Currency(code: "SDG", name: "Sudanese Pound",                symbol: "£",   type: .fiat, flag: "🇸🇩"),
        Currency(code: "SEK", name: "Swedish Krona",                 symbol: "kr",  type: .fiat, flag: "🇸🇪"),
        Currency(code: "SGD", name: "Singapore Dollar",              symbol: "$",   type: .fiat, flag: "🇸🇬"),
        Currency(code: "SHP", name: "St. Helena Pound",              symbol: "£",   type: .fiat, flag: "🇸🇭"),
        Currency(code: "SLE", name: "Sierra Leonean Leone",          symbol: "Le",  type: .fiat, flag: "🇸🇱"),
        Currency(code: "SOS", name: "Somali Shilling",               symbol: "Sh",  type: .fiat, flag: "🇸🇴"),
        Currency(code: "SRD", name: "Surinamese Dollar",             symbol: "$",   type: .fiat, flag: "🇸🇷"),
        Currency(code: "SSP", name: "South Sudanese Pound",          symbol: "£",   type: .fiat, flag: "🇸🇸"),
        Currency(code: "STN", name: "São Tomé & Príncipe Dobra",     symbol: "Db",  type: .fiat, flag: "🇸🇹"),
        Currency(code: "SYP", name: "Syrian Pound",                  symbol: "£",   type: .fiat, flag: "🇸🇾"),
        Currency(code: "SZL", name: "Swazi Lilangeni",               symbol: "L",   type: .fiat, flag: "🇸🇿"),
        Currency(code: "THB", name: "Thai Baht",                     symbol: "฿",   type: .fiat, flag: "🇹🇭"),
        Currency(code: "TJS", name: "Tajikistani Somoni",            symbol: "SM",  type: .fiat, flag: "🇹🇯"),
        Currency(code: "TMT", name: "Turkmenistani Manat",           symbol: "T",   type: .fiat, flag: "🇹🇲"),
        Currency(code: "TND", name: "Tunisian Dinar",                symbol: "د.ت", type: .fiat, flag: "🇹🇳"),
        Currency(code: "TOP", name: "Tongan Paʻanga",                symbol: "T$",  type: .fiat, flag: "🇹🇴"),
        Currency(code: "TRY", name: "Turkish Lira",                  symbol: "₺",   type: .fiat, flag: "🇹🇷"),
        Currency(code: "TTD", name: "Trinidad & Tobago Dollar",      symbol: "$",   type: .fiat, flag: "🇹🇹"),
        Currency(code: "TWD", name: "New Taiwan Dollar",             symbol: "$",   type: .fiat, flag: "🇹🇼"),
        Currency(code: "TZS", name: "Tanzanian Shilling",            symbol: "Sh",  type: .fiat, flag: "🇹🇿"),
        Currency(code: "UAH", name: "Ukrainian Hryvnia",             symbol: "₴",   type: .fiat, flag: "🇺🇦"),
        Currency(code: "UGX", name: "Ugandan Shilling",              symbol: "Sh",  type: .fiat, flag: "🇺🇬"),
        Currency(code: "USD", name: "US Dollar",                     symbol: "$",   type: .fiat, flag: "🇺🇸"),
        Currency(code: "UYU", name: "Uruguayan Peso",                symbol: "$",   type: .fiat, flag: "🇺🇾"),
        Currency(code: "UZS", name: "Uzbekistani Som",               symbol: "so'm",type: .fiat, flag: "🇺🇿"),
        Currency(code: "VES", name: "Venezuelan Bolívar",            symbol: "Bs.S",type: .fiat, flag: "🇻🇪"),
        Currency(code: "VND", name: "Vietnamese Dong",               symbol: "₫",   type: .fiat, flag: "🇻🇳"),
        Currency(code: "VUV", name: "Vanuatu Vatu",                  symbol: "Vt",  type: .fiat, flag: "🇻🇺"),
        Currency(code: "WST", name: "Samoan Tala",                   symbol: "T",   type: .fiat, flag: "🇼🇸"),
        Currency(code: "XAF", name: "CFA Franc BEAC",                symbol: "Fr",  type: .fiat, flag: "🌍"),
        Currency(code: "XCD", name: "East Caribbean Dollar",         symbol: "$",   type: .fiat, flag: "🌎"),
        Currency(code: "XOF", name: "CFA Franc BCEAO",               symbol: "Fr",  type: .fiat, flag: "🌍"),
        Currency(code: "XPF", name: "CFP Franc",                     symbol: "Fr",  type: .fiat, flag: "🌏"),
        Currency(code: "YER", name: "Yemeni Rial",                   symbol: "﷼",   type: .fiat, flag: "🇾🇪"),
        Currency(code: "ZAR", name: "South African Rand",            symbol: "R",   type: .fiat, flag: "🇿🇦"),
        Currency(code: "ZMW", name: "Zambian Kwacha",                symbol: "ZK",  type: .fiat, flag: "🇿🇲"),
        Currency(code: "ZWL", name: "Zimbabwean Dollar",             symbol: "$",   type: .fiat, flag: "🇿🇼"),
    ]

    static let allCrypto: [Currency] = [
        Currency(code: "BTC",   name: "Bitcoin",          symbol: "₿",  type: .crypto, flag: nil),
        Currency(code: "ETH",   name: "Ethereum",         symbol: "Ξ",  type: .crypto, flag: nil),
        Currency(code: "USDT",  name: "Tether",           symbol: "₮",  type: .crypto, flag: nil),
        Currency(code: "USDC",  name: "USD Coin",         symbol: "◈",  type: .crypto, flag: nil),
        Currency(code: "BNB",   name: "BNB",              symbol: "BNB", type: .crypto, flag: nil),
        Currency(code: "SOL",   name: "Solana",           symbol: "◎",  type: .crypto, flag: nil),
        Currency(code: "XRP",   name: "XRP",              symbol: "✕",  type: .crypto, flag: nil),
        Currency(code: "DOGE",  name: "Dogecoin",         symbol: "Ð",  type: .crypto, flag: nil),
        Currency(code: "ADA",   name: "Cardano",          symbol: "₳",  type: .crypto, flag: nil),
        Currency(code: "AVAX",  name: "Avalanche",        symbol: "A",  type: .crypto, flag: nil),
        Currency(code: "SHIB",  name: "Shiba Inu",        symbol: "Ш",  type: .crypto, flag: nil),
        Currency(code: "DOT",   name: "Polkadot",         symbol: "●",  type: .crypto, flag: nil),
        Currency(code: "LINK",  name: "Chainlink",        symbol: "⬡",  type: .crypto, flag: nil),
        Currency(code: "LTC",   name: "Litecoin",         symbol: "Ł",  type: .crypto, flag: nil),
        Currency(code: "UNI",   name: "Uniswap",          symbol: "🦄", type: .crypto, flag: nil),
        Currency(code: "ATOM",  name: "Cosmos",           symbol: "⚛",  type: .crypto, flag: nil),
        Currency(code: "XLM",   name: "Stellar",          symbol: "*",  type: .crypto, flag: nil),
        Currency(code: "NEAR",  name: "NEAR Protocol",    symbol: "Ⓝ",  type: .crypto, flag: nil),
        Currency(code: "ARB",   name: "Arbitrum",         symbol: "A",  type: .crypto, flag: nil),
        Currency(code: "OP",    name: "Optimism",         symbol: "◎",  type: .crypto, flag: nil),
    ]

    static let all: [Currency] = allFiat + allCrypto

    static func find(code: String) -> Currency? {
        all.first { $0.code == code }
    }

    static var usd: Currency { find(code: "USD")! }
    static var eur: Currency { find(code: "EUR")! }
    static var btc: Currency { find(code: "BTC")! }
}
